default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  variables:
    # Maximum time in ms for a single SQL statement to take before it is aborted. 0 means disabled.
    statement_timeout: <%= ENV.fetch('DB_STATEMENT_TIMEOUT_SECONDS', 0).to_i * 1000 %>

development:
  <<: *default
  database: searchna_development

test:
  <<: *default
  database: searchna_test

production:
  <<: *default
  database: searchna
